version: '2'

services:

  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: varejo
    ports:
    - "5431:5432"
    volumes_from:
    - data
    networks:
      - global-network

  data:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: "true"

volumes:
    databasevolume: {}

networks:
    global-network:
        external: true