version: '2'

services:
  base-service:
    container_name: base-service
    build:
      context: ./base-service
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./base-service:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./base-service/.env
    depends_on:
      - postgres_db
    networks:
      - global-network
        
  calculator-service:
    container_name: calculator-service
    build: 
      context: ./calculator-service
    ports:
        - "3333:3333"
    volumes:
        - ./calculator-service:/src
    depends_on:
      - postgres_db
    networks:
        - global-network

  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: varejo
    ports:
    - "5431:5432"
    volumes_from:
    - data
    networks:
      - global-network

  data:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: "true"

volumes:
    databasevolume: {}

networks:
    global-network:
        external: true